/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FavoriteStationIdsResponse = IDL.Variant({
  'ok' : IDL.Vec(IDL.Text),
  'noFavorites' : IDL.Null,
});
export const NonEmptyFavoritesList = IDL.Record({
  'size' : IDL.Nat,
  'values' : IDL.Vec(IDL.Text),
});
export const NonEmptyFavoritesListResponse = IDL.Variant({
  'ok' : NonEmptyFavoritesList,
  'noFavorites' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCalledUserFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoriteStationIds' : IDL.Func([], [FavoriteStationIdsResponse], []),
  'getNonEmptyFavoritesList' : IDL.Func(
      [],
      [NonEmptyFavoritesListResponse],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FavoriteStationIdsResponse = IDL.Variant({
    'ok' : IDL.Vec(IDL.Text),
    'noFavorites' : IDL.Null,
  });
  const NonEmptyFavoritesList = IDL.Record({
    'size' : IDL.Nat,
    'values' : IDL.Vec(IDL.Text),
  });
  const NonEmptyFavoritesListResponse = IDL.Variant({
    'ok' : NonEmptyFavoritesList,
    'noFavorites' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCalledUserFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoriteStationIds' : IDL.Func([], [FavoriteStationIdsResponse], []),
    'getNonEmptyFavoritesList' : IDL.Func(
        [],
        [NonEmptyFavoritesListResponse],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };